### ISSUE TITLE
Finish implementing the `to_mgf` unit test

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/timsrust#1]
Guo Ci implemented a function in `sage` to read `.d` and convert to `.mgf`. It was a shortcut but hard to maintain and test. Ideally, we should implement the unit test function here since it is only about `timsrust` and not related to `sage` at all.

I copied the code to https://github.com/Nesvilab/timsrust/commit/199f87b4bf3b4be3a5640e58f19c1ca753002033. However, it relies on `sage`'s `RawSpectrum`, `Precursor`, and `Representation`. I took a brief look, and they should be easy to be replaced with a simple class.

Enjoy,

Fengchao

**Comment by guoci** [comment]
I have added the dependencies to make the new test compile. Use the following command to run the test.
`cargo test --color=always --package timsrust@0.2.4 --test to_mgf test_mgf --no-fail-fast -- --format=json --exact -Z unstable-options --show-output`
However, I have not implemented the tests yet.

**Comment by fcyu** [comment]
Thanks @guoci , but why did you add sage as dependent? It makes the test clumsy. This is exactly why I created this ticket:

> we should implement the unit test function here since it is only about timsrust and not related to sage at all.

**Comment by RogerLi-97** [comment]
Thanks, and where can I find sage file to locate these three classes?

**Comment by fcyu** [comment]
https://github.com/lazear/sage

But again, there is no need to copy all content of those classes from sage. This unit test just uses them as "place holders". I even think it is a bad idea to use three classes to hold the spectrum. One class should be enough.

**Comment by RogerLi-97** [comment]
Sounds good to me

**Comment by fcyu** [comment]
Implemented in https://github.com/Nesvilab/timsrust/commits/to_mgf/
